spring:
  datasource:
    url: jdbc:postgresql://ec2-54-163-245-3.compute-1.amazonaws.com:5432/ddiuv7a4gl0plp?sslmode=require
    username: hmtrfkxgztmbiq
    password: VLS-O03qOQTeP3bYh1UbwA---y
    driverClassName: org.postgresql.Driver
